// Regenerates fixed/focus-scope.mjs: the installed @radix-ui/react-focus-scope dist with
// patches/@radix-ui+react-focus-scope+<version>.patch applied. Runs on postinstall and before
// `npm run test:fixed`. Fails loudly if the installed version has no patch or the patch no
// longer applies cleanly, so a dependency bump can't silently drift from the fix under test.
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);

// require.resolve lands on the CJS entry (dist/index.js); the ESM build next to it is what
// Vitest loads and what the patch is written against.
const pkgRoot = dirname(dirname(require.resolve('@radix-ui/react-focus-scope')));
const distPath = join(pkgRoot, 'dist', 'index.mjs');
const { version } = JSON.parse(readFileSync(join(pkgRoot, 'package.json'), 'utf8'));
const patchName = `@radix-ui+react-focus-scope+${version}.patch`;
const patchesDir = join(root, 'patches');
if (!readdirSync(patchesDir).includes(patchName)) {
  console.error(`make-fixed: no patch for @radix-ui/react-focus-scope@${version} in patches/ (have: ${readdirSync(patchesDir).join(', ')})`);
  process.exit(1);
}

const original = readFileSync(distPath, 'utf8');
const patched = applyUnifiedDiff(original, readFileSync(join(patchesDir, patchName), 'utf8'));

mkdirSync(join(root, 'fixed'), { recursive: true });
writeFileSync(
  join(root, 'fixed', 'focus-scope.mjs'),
  `// GENERATED by scripts/make-fixed.mjs from @radix-ui/react-focus-scope@${version} dist/index.mjs\n` +
    `// with patches/${patchName} applied. Do not edit; edit the patch.\n` +
    patched
);
console.log(`make-fixed: wrote fixed/focus-scope.mjs (@radix-ui/react-focus-scope@${version} + ${patchName})`);

// Minimal, strict unified-diff applier: each hunk's old side (context + removed lines) must
// occur exactly once in the file. Enough for a hand-written patch; no fuzz, no offsets.
function applyUnifiedDiff(text, diff) {
  const lines = text.split('\n');
  const hunks = [];
  let hunk = null;
  for (const raw of diff.split('\n')) {
    if (raw.startsWith('---') || raw.startsWith('+++')) continue;
    if (raw.startsWith('@@')) {
      hunk = { old: [], new: [] };
      hunks.push(hunk);
      continue;
    }
    if (!hunk) continue;
    if (raw.startsWith('-')) hunk.old.push(raw.slice(1));
    else if (raw.startsWith('+')) hunk.new.push(raw.slice(1));
    else if (raw.startsWith(' ') || raw === '') {
      if (raw === '' && hunk === hunks.at(-1) && diff.endsWith('\n') && raw === diff.split('\n').at(-1)) continue;
      hunk.old.push(raw.slice(1));
      hunk.new.push(raw.slice(1));
    }
  }
  for (const [i, { old, new: replacement }] of hunks.entries()) {
    const matches = [];
    for (let at = 0; at + old.length <= lines.length; at++) {
      if (old.every((l, k) => lines[at + k] === l)) matches.push(at);
    }
    if (matches.length !== 1) {
      console.error(`make-fixed: hunk ${i + 1} of ${patchName} matched ${matches.length} times (expected exactly 1); the installed dist has changed`);
      process.exit(1);
    }
    lines.splice(matches[0], old.length, ...replacement);
  }
  return lines.join('\n');
}
